name: Build plugin

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  PLUGIN_NAME: logseq-plugin-audiosnippet

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp README.md LICENSE package.json icon_512x512.png index.js screenshot.png ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.PLUGIN_NAME }}.zip,package.json"
          token: ${{ secrets.GITHUB_TOKEN }}
