name: Build plugin

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  PLUGIN_NAME: logseq-plugin-audiosnippet

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm ci

      - name: Build with esbuild
        run: npm run build

      - name: Package
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp dist/* ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.PLUGIN_NAME }}.zip,package.json"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
